### ISSUE TITLE
Please enable the syncing of the Tumbleweed and Leap 15.2 vagrant boxes 

### ISSUE THREAD

**Issue by dcermak** [andrii-suse/openqa-trigger-from-obs#59]
The vagrant boxes for openSUSE Tumbleweed and Leap 15.2 were previously synced via rsync.pl to o3, but with the retirement of that script, they no longer appear there.

Could they be included in here please?

The following files were previously synced using these patterns:
1. `Tumbleweed.aarch64-1.0-libvirt_aarch64-Build$BUILD_ID.vagrant.libvirt.box` synced from `openSUSE:Factory:ARM:ToTest/` with the patterns:
```
 '+ /appliances/aarch64/',
 '+ /appliances/*/*vagrant*/',
 '+ */Tumbleweed.aarch64-*.box',
```
2. `Tumbleweed.x86_64-1.0-libvirt-Build$BUILD_ID.vagrant.libvirt.box` and `Tumbleweed.x86_64-1.0-virtualbox-Build$BUILD_ID.vagrant.virtualbox.box` synced from `openSUSE:Factory:ToTest` with these patterns:
```
 '+ /appliances/*/*vagrant*/',
 '+ */Tumbleweed.x86_64-*.box',
```
3. `Leap-15.2.aarch64-15.2-libvirt_aarch64-Build$BUILD_ID.vagrant.libvirt.box` synced from `openSUSE:Leap:15.2:ARM:Images:ToTest/images/` using these patterns:
```
 '+ /aarch64/*vagrant*/',
 '+ */Leap-15.2.aarch64-*.box',
```
4. `Leap-15.2.x86_64-15.2-libvirt-Build$BUILD_ID.vagrant.libvirt.box` and `Leap-15.2.x86_64-15.2-virtualbox-Build$BUILD_ID.vagrant.virtualbox.box` synced from `openSUSE:Leap:15.2:Images:ToTest` using these patterns:
```
 '+ /x86_64/*vagrant*/',
 '+ */Leap-15.2.x86_64-*.box',
```

**Comment by andrii-suse** [comment]
As we discussed in private - only syncing will not work, because OpenQA will clean up all not registered assets http://open.qa/docs/#_asset_cleanup
Thus every file must be registered as part of `isos post` call.
I've added that for tw in #60, and for leap in #63 and #64, so the boxes will be copied and registered properly.
